# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: required
cache: packages

apt_packages:
  - fort77

r_binary_packages: 
  - stringr
  - dplyr
  - igraph
  - RCurl
  - XML
  - git2r
  
warnings_are_errors: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
env:
  - R_REMOTES_UPGRADE="always"  
  
before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
  - echo 'options(Ncpus = 2)' > ~/.Rprofile
  - sudo apt-get -qq update
  - sudo apt-get install -y libpng-dev  
